name: Build SwiftShader (Windows)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest
    env:
      CMAKE_BUILD_TYPE: Release
      BUILD_TARGET: vk_swiftshader   # change to another target if you prefer
      ARCH: x64

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure CMake
        run: |
          mkdir -Force build
          cmake -S . -B build -A ${{ env.ARCH }} -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }}

      - name: Build SwiftShader target
        run: cmake --build build --config ${{ env.CMAKE_BUILD_TYPE }} --target ${{ env.BUILD_TARGET }} --parallel

      - name: Show build output (debug)
        run: |
          echo "=== DLLs found ==="
          Get-ChildItem -Path build -Filter *.dll -Recurse -ErrorAction SilentlyContinue | ForEach-Object { $_.FullName }
          echo "=== ICD JSON (if generated) ==="
          Get-ChildItem -Path build -Filter vk_swiftshader_icd.json -Recurse -ErrorAction SilentlyContinue | ForEach-Object { $_.FullName }

      - name: Upload built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: swiftshader-windows
          path: |
            build/**/*.dll
            build/**/*.lib
            build/**/*.pdb
            build/**/vk_swiftshader_icd.json
